# Generated by Django 3.2.6 on 2022-03-28 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membership', '0003_alter_gccustomersubscription_upcoming_payments'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StripeSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
                ('upcoming_payments', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.stripecustomer', unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='gccustomer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='gccustomersubscription',
            name='customer',
        ),
        migrations.DeleteModel(
            name='BankDetailsFlowSession',
        ),
        migrations.DeleteModel(
            name='GCCustomerSubscription',
        ),
        migrations.AlterField(
            model_name='usersubscriptioncancelled',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.stripecustomer'),
        ),
        migrations.DeleteModel(
            name='GCCustomer',
        ),
    ]
