# Generated by Django 3.1.7 on 2021-06-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
