# Generated by Django 3.1.7 on 2021-07-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=150, unique=True)),
                ('customer', models.CharField(max_length=150)),
                ('mandate', models.CharField(max_length=150)),
                ('subscription', models.CharField(max_length=150)),
                ('active', models.BooleanField()),
                ('api_type', models.CharField(choices=[('stripe', 'Stripe'), ('go_cardless', 'Go Cardless')], default='stripe', max_length=20)),
            ],
        ),
    ]
