# Generated by Django 3.1.7 on 2021-05-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useravatar',
            name='type',
        ),
        migrations.AlterField(
            model_name='useravatar',
            name='image',
            field=models.ImageField(upload_to='Avatar'),
        ),
    ]
