# Generated by Django 3.1.7 on 2021-05-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0003_auto_20210508_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravatar',
            name='image',
            field=models.FileField(upload_to='avatar'),
        ),
    ]
