# Generated by Django 3.1.7 on 2021-05-08 15:16

from django.db import migrations, models
import user_account.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0005_auto_20210508_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravatar',
            name='image',
            field=models.ImageField(upload_to=user_account.models.upload_path),
        ),
    ]
