# Generated by Django 3.1.7 on 2021-08-21 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0005_pairedaccounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedJointAcount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.membershipstatus')),
            ],
        ),
        migrations.CreateModel(
            name='MainJointAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainjointaccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.membershipstatus')),
            ],
        ),
        migrations.DeleteModel(
            name='PairedAccounts',
        ),
        migrations.AddField(
            model_name='linkedjointacount',
            name='mainjointaccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.mainjointaccount'),
        ),
    ]
