# Generated by Django 3.1.7 on 2021-08-21 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0007_auto_20210821_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkedacount',
            old_name='mainjointaccount',
            new_name='main_joint_account',
        ),
        migrations.RenameField(
            model_name='mainjointaccount',
            old_name='mainjointaccount',
            new_name='main_joint_account',
        ),
    ]
