# Generated by Django 3.1.7 on 2021-08-21 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0009_auto_20210821_1734'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LinkedAcount',
            new_name='LinkedAccount',
        ),
    ]
