# Generated by Django 3.1.7 on 2021-05-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0009_auto_20210508_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravatar',
            name='image',
            field=models.CharField(max_length=150),
        ),
    ]
