# Generated by Django 3.1.7 on 2021-05-10 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0010_auto_20210510_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useravatar',
            old_name='image',
            new_name='image_name',
        ),
    ]
