# Generated by Django 3.1.7 on 2021-08-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0010_auto_20210821_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipstatus',
            name='api_type',
            field=models.CharField(choices=[('none', 'No Api'), ('stripe', 'Stripe'), ('go_cardless', 'Go Cardless')], default='stripe', max_length=20),
        ),
    ]
