# Generated by Django 3.1.7 on 2021-08-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0011_auto_20210822_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipstatus',
            name='active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membershipstatus',
            name='customer_id',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='membershipstatus',
            name='mandate_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='membershipstatus',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
