# Generated by Django 3.1.7 on 2021-08-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0012_auto_20210822_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
