# Generated by Django 3.1.7 on 2021-08-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0014_delete_manualupload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershipstatus',
            options={'verbose_name_plural': 'Membership Status'},
        ),
        migrations.AlterModelOptions(
            name='passwordresets',
            options={'verbose_name_plural': 'Password Resets'},
        ),
        migrations.AlterField(
            model_name='membershipstatus',
            name='api_type',
            field=models.CharField(choices=[('none', 'No Api'), ('stripe', 'Stripe'), ('go_cardless', 'Go Cardless'), ('manual', 'Manual')], default='stripe', max_length=20),
        ),
    ]
