# Generated by Django 3.1.7 on 2021-08-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0016_auto_20210823_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipstatus',
            name='api_type',
            field=models.CharField(choices=[('go_cardless', 'Go Cardless'), ('manual', 'Manual')], default='manual', max_length=20),
        ),
    ]
