# Generated by Django 3.1.7 on 2021-09-27 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_account', '0017_auto_20210823_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDeviceID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=250)),
                ('device_type', models.CharField(choices=[('ios', 'Ios'), ('android', 'Android')], default='android', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
