# Generated by Django 3.2.6 on 2021-11-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0019_auto_20210927_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipstatus',
            name='force_active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
