# Generated by Django 3.2.6 on 2022-01-05 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0020_membershipstatus_force_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainjointaccount',
            name='main_joint_account',
        ),
        migrations.RemoveField(
            model_name='membershipstatus',
            name='api_type',
        ),
        migrations.RemoveField(
            model_name='membershipstatus',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='membershipstatus',
            name='force_active',
        ),
        migrations.RemoveField(
            model_name='membershipstatus',
            name='mandate_id',
        ),
        migrations.RemoveField(
            model_name='membershipstatus',
            name='subscription_id',
        ),
        migrations.DeleteModel(
            name='LinkedAccount',
        ),
        migrations.DeleteModel(
            name='MainJointAccount',
        ),
    ]
