# Generated by Django 3.2.6 on 2022-01-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0022_awaitingactivation'),
    ]

    operations = [
        migrations.AddField(
            model_name='awaitingactivation',
            name='email',
            field=models.CharField(default='email@email.com', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='awaitingactivation',
            name='name',
            field=models.CharField(default='Joe Bloggo', max_length=300),
            preserve_default=False,
        ),
    ]
