# Generated by Django 3.2.6 on 2022-01-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0023_auto_20220105_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipstatus',
            name='active',
            field=models.BooleanField(blank=True, default=True),
            preserve_default=False,
        ),
    ]
