# Generated by Django 3.1.7 on 2021-06-22 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20210621_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreplies',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='feed.post'),
            preserve_default=False,
        ),
    ]
