# Generated by Django 3.1.7 on 2021-08-04 15:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20210721_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail_link',
            field=models.TextField(default=datetime.datetime(2021, 8, 4, 15, 32, 51, 327879, tzinfo=utc), max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='vimeo_id',
            field=models.CharField(default=datetime.datetime(2021, 8, 4, 15, 33, 0, 552723, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
