# Generated by Django 3.1.7 on 2021-08-07 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20210804_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='vimeo_id',
        ),
        migrations.AddField(
            model_name='post',
            name='video_link',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
