# Generated by Django 3.1.7 on 2021-06-22 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_commentreplies_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentreplies',
            old_name='PostComment',
            new_name='post_comment',
        ),
    ]
