# Generated by Django 3.1.7 on 2021-08-07 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20210807_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='video_link',
            new_name='video_id',
        ),
    ]
