# Generated by Django 3.1.7 on 2021-08-07 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_post_video_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video_name',
        ),
    ]
