# Generated by Django 3.1.7 on 2021-06-30 12:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0006_auto_20210630_0941'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postcommentlikes',
            unique_together={('user', 'post_comment')},
        ),
        migrations.AlterUniqueTogether(
            name='replyreplylikes',
            unique_together={('user', 'comment_reply')},
        ),
    ]
