# Generated by Django 3.2.6 on 2021-11-01 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_post_time_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
