# Generated by Django 3.1.7 on 2021-07-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live', models.BooleanField(default=False)),
                ('time_from', models.CharField(max_length=150)),
                ('time_to', models.CharField(max_length=150)),
                ('excercise', models.CharField(max_length=150)),
                ('instructor', models.CharField(max_length=150)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=20)),
            ],
        ),
    ]
