# Generated by Django 3.1.7 on 2021-07-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='time_from',
            field=models.TimeField(max_length=150),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='time_to',
            field=models.TimeField(max_length=150),
        ),
    ]
