# Generated by Django 3.1.7 on 2021-05-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
