# Generated by Django 3.1.7 on 2021-05-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_chatuser_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
