# Generated by Django 3.1.7 on 2021-06-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_chatuser_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.CharField(max_length=1000),
        ),
    ]
