# Generated by Django 3.1.7 on 2021-07-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VimeoVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vimeo_id', models.CharField(max_length=100)),
                ('name', models.TextField(max_length=250)),
                ('file_link', models.TextField(max_length=250)),
                ('thumbnail_link', models.TextField(max_length=250)),
                ('last_updated', models.DateTimeField()),
                ('type', models.CharField(choices=[('Post', 'Post Video'), ('Feed', 'Feed Video')], max_length=20)),
            ],
        ),
    ]
