# Generated by Django 3.1.7 on 2021-07-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_stream', '0002_vimeovideos_upload_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vimeovideos',
            old_name='upload_data',
            new_name='upload_date',
        ),
        migrations.AlterField(
            model_name='vimeovideos',
            name='type',
            field=models.CharField(choices=[('OldStream', 'Old Stream'), ('Feed', 'Feed Video')], max_length=20),
        ),
    ]
