# Generated by Django 3.1.7 on 2021-08-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_stream', '0003_auto_20210726_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='VimeoLiveStreams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=250)),
                ('stream_url', models.TextField(max_length=250)),
                ('chat_url', models.TextField(max_length=250)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=20)),
            ],
        ),
    ]
