# Generated by Django 3.1.7 on 2021-08-03 15:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('live_stream', '0004_vimeolivestreams'),
    ]

    operations = [
        migrations.AddField(
            model_name='vimeolivestreams',
            name='time_from',
            field=models.TimeField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vimeolivestreams',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 8, 3, 15, 6, 21, 735800, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
