# Generated by Django 3.1.7 on 2021-08-04 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_stream', '0006_auto_20210803_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vimeovideos',
            old_name='file_link',
            new_name='video_url',
        ),
    ]
