# Generated by Django 3.1.7 on 2021-08-23 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_stream', '0007_auto_20210804_0901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vimeolivestreams',
            options={'verbose_name_plural': 'Vimeo Live Streams'},
        ),
    ]
