# Generated by Django 3.1.7 on 2021-08-24 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_stream', '0008_auto_20210823_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vimeolivestreams',
            name='chat_url',
        ),
    ]
